### ISSUE TITLE
error when running pipeline

### ISSUE THREAD

**Issue by baynewc1** [enufacas/azureDevOps.CostSavings#2]
when running the script in a pipeline it immediately fails with an error:
![image](https://user-images.githubusercontent.com/7177740/81021576-8d600780-8ebf-11ea-9e10-a333ac04c6ca.png)

**Comment by enufacas** [comment]
Hey sorry you are having problems, make sure the build-service has the right permissions mentioned in the blog post. 

Specifically:
- The Project Collection Build Service will need [View Analytics](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-security?view=azure-devops#set-permissions) rights for the project the pipeline is running in. 

If you are still having issues after that and want to run the pipeline in debug and share the error, I will be happy to help!

**Comment by enufacas** [comment]
Hey @baynewc1 in testing the pipeline out in a few more environments tonight I ran into an issue in an environment that was using the newer style url formats. I am guessing that you may have had the same problem. 
For example take  `https://dev.azure.com/fabrikamfiber/ ` vs `https://fabrikamfiber.visualstudio.com/`

There is not really a first class Environment Variable available for the collection name so that is why I am splitting it out of `$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI`. I added a bit of logic that should handle both the new format and the old format. 

```
$CollectionName = ([System.Uri]$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI).Host.split('.')[-3]

if ($CollectionName -eq 'dev'){
    $CollectionName = ($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI).split('/')[-2]
}
```
I hope that helps. I will keep this one open for a bit or until I hear back from you!
